version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "${DB_USERNAME}"
      # You can use whatever password you like
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "${DB_PORT}:3306"
    expose:
      # Opens port 3306 on the container
      - "${DB_PORT}"
      # Where our data will be persisted
    volumes:
      - my-db:${HOME}/.docker/volume/mysql
# Names our volume
volumes:
  my-db:
