apiVersion: apps/v1
kind: Deployment
metadata:
  name: bakery-deployment
  labels:
    app: bakery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bakery
  template:
    metadata:
      labels:
        app: bakery
        database_service: mysql
    spec:
      containers:
      - name: bakery
        image: smontecinos695/bakery:0.0.1
        ports:
        - containerPort: 5000
