apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    database-service: mysql
  clusterIP: None


apiVersion: v1
kind: Service
metadata:
  name: bakery
spec:
  selector:
    app:  bakery
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: NodePort
